ALTER TABLE pages ADD COLUMN meta_keywords VARCHAR(300);
ALTER TABLE pages ADD COLUMN og_title VARCHAR(200);
ALTER TABLE pages ADD COLUMN og_description VARCHAR(500);
ALTER TABLE pages ADD COLUMN noindex BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE pages ADD COLUMN nofollow BOOLEAN NOT NULL DEFAULT false;
